{% set name = "mobie" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d4457e7236f609463a8299034da5dd481f49227c2423b8dcc3a0134184d6986

build:
  noarch: python
  number: 0
  entry_points:
    - mobie=mobie:launch_mobie
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jgo >=0.4.0
    - pip
    - python
  run:
    - jgo >=0.4.0
    - python >=3.7
    - openjdk =8
    - maven
    - blosc

test:
  imports:
    - mobie
  commands:
    - mobie --help

about:
  home: https://github.com/mobie/mobie-cmd
  license: BSD-2-clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Viewer for big multi-modal image data

extra:
  recipe-maintainers:
    - tischi
